version: '3.8'

services:
  web:
    build:
      context: ./bin/php83
    container_name: strkz_api_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
    links:
      - db

    environment:
      PMA_PORT: ${PMA_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${MYSQL_PORT}

    extra_hosts:
      - "host.docker.internal:host-gateway"


  db:
    build:
      context: "./bin/mysql8"
    restart: "always"
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${MYSQL_PORT}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "127.0.0.1:${MYSQL_PORT}:3306"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db

